### ISSUE TITLE
ProFTPD

### ISSUE THREAD

**Issue by johnny-mac** [NeoChontrix/void-packages#2]
I was wondering if I could get you to package ProFTPD, in my opinion its the best FTP daemon. bftpd, vsftpd, & twoftpd are a pain, I can't seem to make any of them work properly, except proftpd, and if I can make proftpd work then that means anyone can make it work :P 

ProFTPD compiles without issue on void, but I don't know if it works on Void, as I couldn't make it work myself but am going to try again, the experience I speak of with FTP daemons is with Devuan Linux.

Thank you very much for packaging Barrier!

**Comment by johnny-mac** [comment]
And on Barrier, should "Don't take foreground window on Windows servers"
mean that when I take the mouse onto another screen, the window on the previous screen won't become the inactive window? I'm having trouble understanding what this setting is supposed to do, am I misunderstanding it or perhaps does it not work as intended?

**Comment by Johnnynator** [comment]
> And on Barrier, should "Don't take foreground window on Windows servers"
> mean that when I take the mouse onto another screen, the window on the previous screen won't become the inactive window? I'm having trouble understanding what this setting is supposed to do, am I misunderstanding it or perhaps does it not work as intended?

Don't ask me what this option does. I don't know more than you
